### ISSUE TITLE
How can i put the index.js from webpack before the loaded cdn?

### ISSUE THREAD

**Issue by yellooo** [xalexec/public-cdn-webpack-plugin#1]
Hi, i search a way to put the minified index.js before the cdn? Any ideas?

**Comment by xalexec** [comment]
I did't understand why minified before the cdn. 
maybe you can use like this
````
{
  src: 'http://abc.com/xx.js',
  defer: true
}
````

**Comment by yellooo** [comment]
The defer works good thx
